#!/bin/bash

# USAGE: 
# run sim [rebuild] -- runs on simpixel with optional rebuild of Bibliopixel
# run ap [rebuild] -- runs on 3 all pixels with optional rebuild of Bibliopixel

# First install bibliopixel
if [[ "$2" == "rebuild" ]]; then
	echo "Rebuilding..."
	cd ~/BiblioPixel
	sudo python3 setup.py install &> ~/LED/log.txt
	cd ~/LED
fi

cp PartyRemote.json PartyRemoteCompiled.json

if [[ "$1" == "ap" ]]; then
    echo "Run USB"
    echo ',"c_order": "BGR"}, "drivers": [{"device_id": 1},{"device_id": 2},{"device_id": 3}]}' >> PartyRemoteCompiled.json
    ~/BiblioPixel/scripts/bibliopixel run PartyRemoteCompiled.json -d "serial" -t "APA102"
else
    echo '}}' >> PartyRemoteCompiled.json
    ~/BiblioPixel/scripts/bibliopixel run PartyRemoteCompiled.json -d "simpixel"
fi
