#!/bin/sh
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Raspberry
    ~/BiblioPixel/scripts/bibliopixel run PartyRemote.json -d "serial" -t "APA102" -j "'drivers': [{'device_id': 1},{'device_id': 2}]"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    ~/BiblioPixel/scripts/bibliopixel run PartyRemote.json -d "simpixel"
fi
